// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/cluster.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cluster messages
type ListClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersRequest.ProtoReflect.Descriptor instead.
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{0}
}

type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ListClustersResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	CloudProvider string                 `protobuf:"bytes,3,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Cluster) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *Cluster) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Cluster) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type VerifyClusterExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyClusterExistsRequest) Reset() {
	*x = VerifyClusterExistsRequest{}
	mi := &file_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyClusterExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyClusterExistsRequest) ProtoMessage() {}

func (x *VerifyClusterExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyClusterExistsRequest.ProtoReflect.Descriptor instead.
func (*VerifyClusterExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyClusterExistsRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type VerifyClusterExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyClusterExistsResponse) Reset() {
	*x = VerifyClusterExistsResponse{}
	mi := &file_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyClusterExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyClusterExistsResponse) ProtoMessage() {}

func (x *VerifyClusterExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyClusterExistsResponse.ProtoReflect.Descriptor instead.
func (*VerifyClusterExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyClusterExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *VerifyClusterExistsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetClusterDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterDetailsRequest) Reset() {
	*x = GetClusterDetailsRequest{}
	mi := &file_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterDetailsRequest) ProtoMessage() {}

func (x *GetClusterDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetClusterDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *GetClusterDetailsRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type GetClusterDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ClusterConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterDetailsResponse) Reset() {
	*x = GetClusterDetailsResponse{}
	mi := &file_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterDetailsResponse) ProtoMessage() {}

func (x *GetClusterDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetClusterDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *GetClusterDetailsResponse) GetConfig() *ClusterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetClusterDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClusterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	CloudProvider string                 `protobuf:"bytes,3,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	ClusterToken  string                 `protobuf:"bytes,6,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterConfig) Reset() {
	*x = ClusterConfig{}
	mi := &file_proto_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfig) ProtoMessage() {}

func (x *ClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfig.ProtoReflect.Descriptor instead.
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ClusterConfig) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *ClusterConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ClusterConfig) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ClusterConfig) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

type CreateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CloudProvider string                 `protobuf:"bytes,3,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Bucket        string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_proto_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *CreateClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateClusterRequest) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *CreateClusterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateClusterRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CreateClusterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ClusterConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterResponse) Reset() {
	*x = CreateClusterResponse{}
	mi := &file_proto_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterResponse) ProtoMessage() {}

func (x *CreateClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterResponse.ProtoReflect.Descriptor instead.
func (*CreateClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *CreateClusterResponse) GetConfig() *ClusterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateClusterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Bucket messages
type ListBucketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudProvider string                 `protobuf:"bytes,1,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsRequest) Reset() {
	*x = ListBucketsRequest{}
	mi := &file_proto_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsRequest) ProtoMessage() {}

func (x *ListBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *ListBucketsRequest) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

type ListBucketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*Bucket              `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsResponse) Reset() {
	*x = ListBucketsResponse{}
	mi := &file_proto_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsResponse) ProtoMessage() {}

func (x *ListBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ListBucketsResponse) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type Bucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	mi := &file_proto_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *Bucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bucket) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Bucket) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Bucket) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Bucket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type VerifyBucketAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudProvider string                 `protobuf:"bytes,1,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBucketAccessRequest) Reset() {
	*x = VerifyBucketAccessRequest{}
	mi := &file_proto_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBucketAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBucketAccessRequest) ProtoMessage() {}

func (x *VerifyBucketAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBucketAccessRequest.ProtoReflect.Descriptor instead.
func (*VerifyBucketAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyBucketAccessRequest) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *VerifyBucketAccessRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *VerifyBucketAccessRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type VerifyBucketAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBucketAccessResponse) Reset() {
	*x = VerifyBucketAccessResponse{}
	mi := &file_proto_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBucketAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBucketAccessResponse) ProtoMessage() {}

func (x *VerifyBucketAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBucketAccessResponse.ProtoReflect.Descriptor instead.
func (*VerifyBucketAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyBucketAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *VerifyBucketAccessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckResourceReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudProvider string                 `protobuf:"bytes,1,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResourceReadinessRequest) Reset() {
	*x = CheckResourceReadinessRequest{}
	mi := &file_proto_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResourceReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResourceReadinessRequest) ProtoMessage() {}

func (x *CheckResourceReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResourceReadinessRequest.ProtoReflect.Descriptor instead.
func (*CheckResourceReadinessRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *CheckResourceReadinessRequest) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *CheckResourceReadinessRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CheckResourceReadinessRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CheckResourceReadinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResourceReadinessResponse) Reset() {
	*x = CheckResourceReadinessResponse{}
	mi := &file_proto_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResourceReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResourceReadinessResponse) ProtoMessage() {}

func (x *CheckResourceReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResourceReadinessResponse.ProtoReflect.Descriptor instead.
func (*CheckResourceReadinessResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *CheckResourceReadinessResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *CheckResourceReadinessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_cluster_proto protoreflect.FileDescriptor

const file_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x13proto/cluster.proto\x12\acluster\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n" +
	"\x13ListClustersRequest\"D\n" +
	"\x14ListClustersResponse\x12,\n" +
	"\bclusters\x18\x01 \x03(\v2\x10.cluster.ClusterR\bclusters\"\x84\x01\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12%\n" +
	"\x0ecloud_provider\x18\x03 \x01(\tR\rcloudProvider\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"?\n" +
	"\x1aVerifyClusterExistsRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\"K\n" +
	"\x1bVerifyClusterExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"=\n" +
	"\x18GetClusterDetailsRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\"a\n" +
	"\x19GetClusterDetailsResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.cluster.ClusterConfigR\x06config\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb3\x01\n" +
	"\rClusterConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12%\n" +
	"\x0ecloud_provider\x18\x03 \x01(\tR\rcloudProvider\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12#\n" +
	"\rcluster_token\x18\x06 \x01(\tR\fclusterToken\"\xa9\x01\n" +
	"\x14CreateClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12%\n" +
	"\x0ecloud_provider\x18\x03 \x01(\tR\rcloudProvider\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"]\n" +
	"\x15CreateClusterResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.cluster.ClusterConfigR\x06config\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\";\n" +
	"\x12ListBucketsRequest\x12%\n" +
	"\x0ecloud_provider\x18\x01 \x01(\tR\rcloudProvider\"@\n" +
	"\x13ListBucketsResponse\x12)\n" +
	"\abuckets\x18\x01 \x03(\v2\x0f.cluster.BucketR\abuckets\"\x9f\x01\n" +
	"\x06Bucket\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"n\n" +
	"\x19VerifyBucketAccessRequest\x12%\n" +
	"\x0ecloud_provider\x18\x01 \x01(\tR\rcloudProvider\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"Q\n" +
	"\x1aVerifyBucketAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"r\n" +
	"\x1dCheckResourceReadinessRequest\x12%\n" +
	"\x0ecloud_provider\x18\x01 \x01(\tR\rcloudProvider\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"L\n" +
	"\x1eCheckResourceReadinessResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xf3\x02\n" +
	"\x0eClusterService\x12M\n" +
	"\fListClusters\x12\x1c.cluster.ListClustersRequest\x1a\x1d.cluster.ListClustersResponse\"\x00\x12b\n" +
	"\x13VerifyClusterExists\x12#.cluster.VerifyClusterExistsRequest\x1a$.cluster.VerifyClusterExistsResponse\"\x00\x12\\\n" +
	"\x11GetClusterDetails\x12!.cluster.GetClusterDetailsRequest\x1a\".cluster.GetClusterDetailsResponse\"\x00\x12P\n" +
	"\rCreateCluster\x12\x1d.cluster.CreateClusterRequest\x1a\x1e.cluster.CreateClusterResponse\"\x002\xa9\x02\n" +
	"\rBucketService\x12J\n" +
	"\vListBuckets\x12\x1b.cluster.ListBucketsRequest\x1a\x1c.cluster.ListBucketsResponse\"\x00\x12_\n" +
	"\x12VerifyBucketAccess\x12\".cluster.VerifyBucketAccessRequest\x1a#.cluster.VerifyBucketAccessResponse\"\x00\x12k\n" +
	"\x16CheckResourceReadiness\x12&.cluster.CheckResourceReadinessRequest\x1a'.cluster.CheckResourceReadinessResponse\"\x00B0Z.github.com/nstream-ai/mothership/proto/clusterb\x06proto3"

var (
	file_proto_cluster_proto_rawDescOnce sync.Once
	file_proto_cluster_proto_rawDescData []byte
)

func file_proto_cluster_proto_rawDescGZIP() []byte {
	file_proto_cluster_proto_rawDescOnce.Do(func() {
		file_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cluster_proto_rawDesc), len(file_proto_cluster_proto_rawDesc)))
	})
	return file_proto_cluster_proto_rawDescData
}

var file_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_cluster_proto_goTypes = []any{
	(*ListClustersRequest)(nil),            // 0: cluster.ListClustersRequest
	(*ListClustersResponse)(nil),           // 1: cluster.ListClustersResponse
	(*Cluster)(nil),                        // 2: cluster.Cluster
	(*VerifyClusterExistsRequest)(nil),     // 3: cluster.VerifyClusterExistsRequest
	(*VerifyClusterExistsResponse)(nil),    // 4: cluster.VerifyClusterExistsResponse
	(*GetClusterDetailsRequest)(nil),       // 5: cluster.GetClusterDetailsRequest
	(*GetClusterDetailsResponse)(nil),      // 6: cluster.GetClusterDetailsResponse
	(*ClusterConfig)(nil),                  // 7: cluster.ClusterConfig
	(*CreateClusterRequest)(nil),           // 8: cluster.CreateClusterRequest
	(*CreateClusterResponse)(nil),          // 9: cluster.CreateClusterResponse
	(*ListBucketsRequest)(nil),             // 10: cluster.ListBucketsRequest
	(*ListBucketsResponse)(nil),            // 11: cluster.ListBucketsResponse
	(*Bucket)(nil),                         // 12: cluster.Bucket
	(*VerifyBucketAccessRequest)(nil),      // 13: cluster.VerifyBucketAccessRequest
	(*VerifyBucketAccessResponse)(nil),     // 14: cluster.VerifyBucketAccessResponse
	(*CheckResourceReadinessRequest)(nil),  // 15: cluster.CheckResourceReadinessRequest
	(*CheckResourceReadinessResponse)(nil), // 16: cluster.CheckResourceReadinessResponse
	(*timestamppb.Timestamp)(nil),          // 17: google.protobuf.Timestamp
}
var file_proto_cluster_proto_depIdxs = []int32{
	2,  // 0: cluster.ListClustersResponse.clusters:type_name -> cluster.Cluster
	7,  // 1: cluster.GetClusterDetailsResponse.config:type_name -> cluster.ClusterConfig
	7,  // 2: cluster.CreateClusterResponse.config:type_name -> cluster.ClusterConfig
	12, // 3: cluster.ListBucketsResponse.buckets:type_name -> cluster.Bucket
	17, // 4: cluster.Bucket.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: cluster.ClusterService.ListClusters:input_type -> cluster.ListClustersRequest
	3,  // 6: cluster.ClusterService.VerifyClusterExists:input_type -> cluster.VerifyClusterExistsRequest
	5,  // 7: cluster.ClusterService.GetClusterDetails:input_type -> cluster.GetClusterDetailsRequest
	8,  // 8: cluster.ClusterService.CreateCluster:input_type -> cluster.CreateClusterRequest
	10, // 9: cluster.BucketService.ListBuckets:input_type -> cluster.ListBucketsRequest
	13, // 10: cluster.BucketService.VerifyBucketAccess:input_type -> cluster.VerifyBucketAccessRequest
	15, // 11: cluster.BucketService.CheckResourceReadiness:input_type -> cluster.CheckResourceReadinessRequest
	1,  // 12: cluster.ClusterService.ListClusters:output_type -> cluster.ListClustersResponse
	4,  // 13: cluster.ClusterService.VerifyClusterExists:output_type -> cluster.VerifyClusterExistsResponse
	6,  // 14: cluster.ClusterService.GetClusterDetails:output_type -> cluster.GetClusterDetailsResponse
	9,  // 15: cluster.ClusterService.CreateCluster:output_type -> cluster.CreateClusterResponse
	11, // 16: cluster.BucketService.ListBuckets:output_type -> cluster.ListBucketsResponse
	14, // 17: cluster.BucketService.VerifyBucketAccess:output_type -> cluster.VerifyBucketAccessResponse
	16, // 18: cluster.BucketService.CheckResourceReadiness:output_type -> cluster.CheckResourceReadinessResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_cluster_proto_init() }
func file_proto_cluster_proto_init() {
	if File_proto_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cluster_proto_rawDesc), len(file_proto_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_cluster_proto_goTypes,
		DependencyIndexes: file_proto_cluster_proto_depIdxs,
		MessageInfos:      file_proto_cluster_proto_msgTypes,
	}.Build()
	File_proto_cluster_proto = out.File
	file_proto_cluster_proto_goTypes = nil
	file_proto_cluster_proto_depIdxs = nil
}
